from mipaquete.modelo import *
e=Empleado()
e.agregar_nombre("Luis")
e.agregar_apellido("Benitez")	
e.agregar_cedula("110101")
print(e.presentar_datos())

e1=EmpleadoPorHoras()
nombre = input("Ingrese su nombre")
e1.agregar_nombre(nombre)
e1.agregar_apellido("Andrade")
e1.agregar_cedula("111222333")
e1.agregar_numero_horas(15)
e1.agregar_valor_horas(20.2)
print(e1.presentar_datos())

e2= EmpleadoFijo()
e2.agregar_sueldof(300.2)
e2.agregar_descuentos(10) #Porcentaje
comision = input("Ingrese la comision")
comision = float(comision)
e2.agregar_comisionf(comision)
e2.agregar_nombre("Ana")
e2.agregar_apellido("Diaz")
print(e2.presentar_datos())